# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  petstoreAPITests:
    docker:
      # specify the version you desire here
      - image: maven:3.6.3-adoptopenjdk-8
    steps:
      - checkout
      - run:
          name: Run Petstore Tests
          command: mvn verify
      - store_artifacts:
          path: /root/project/target/failsafe-reports
workflows:
  # Name the workflow "petStoreApiPipeline"
  API Tests Maven JDK 8:
    # Run pet store tests
    jobs:
      - petstoreAPITests:
          filters:
            branches:
              only: main
